In [43]:
import numpy as np

In [44]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [45]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [47]:
arr.ndim

1

In [48]:
arr2.ndim

2

In [49]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr.shape

(4,)

In [51]:
arr8=np.arange(1,11)
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr6=np.arange(10,21)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
zero_matri=np.zeros((3,3))
zero_matri

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
one_matri=np.ones((4,4))
one_matri

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
random_matrix2=np.random.randint(1,11,size=(3,3))
random_matrix2

array([[7, 5, 1],
       [8, 8, 8],
       [1, 6, 7]])

In [56]:
arr8=np.arange(1,51)
arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [57]:
arr1=np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
arr2=np.ones((4,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
import numpy as np
a=np.arange(4)
a

array([0, 1, 2, 3])

In [60]:
b=np.arange(10,14)
b

array([10, 11, 12, 13])

In [61]:
c=a+b
c

array([10, 12, 14, 16])

In [62]:
a-b

array([-10, -10, -10, -10])

In [63]:
a*b

array([ 0, 11, 24, 39])

In [64]:
a*2

array([0, 2, 4, 6])

In [65]:
a*3

array([0, 3, 6, 9])

In [66]:
b<10

array([False, False, False, False])

In [67]:
b<12

array([ True,  True, False, False])

In [8]:
import numpy as np

d=np.arange(1,13)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
e=d.reshape(3,4)
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
e.ndim
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
e.sum()

66

In [72]:
e.max()

11

In [73]:
e.min()

0

In [74]:
e.mean()

5.5

In [75]:
dt=np.dtype(np.int32)
dt

dtype('int32')

In [76]:
e.min(axis=1)

array([0, 4, 8])

In [77]:
e.min(axis=0)

array([0, 1, 2, 3])

In [78]:
e.sum(axis=0)

array([12, 15, 18, 21])

In [79]:
z=np.random.random((3,4))
z

array([[0.41347616, 0.3939117 , 0.52663996, 0.31542709],
       [0.36748118, 0.99429711, 0.46012885, 0.1928901 ],
       [0.9712583 , 0.12581869, 0.84606985, 0.54787334]])

In [80]:
z.shape

(3, 4)

In [81]:
x=z.reshape(6,2)
x

array([[0.41347616, 0.3939117 ],
       [0.52663996, 0.31542709],
       [0.36748118, 0.99429711],
       [0.46012885, 0.1928901 ],
       [0.9712583 , 0.12581869],
       [0.84606985, 0.54787334]])

In [82]:
z

array([[0.41347616, 0.3939117 , 0.52663996, 0.31542709],
       [0.36748118, 0.99429711, 0.46012885, 0.1928901 ],
       [0.9712583 , 0.12581869, 0.84606985, 0.54787334]])

In [83]:
x.ravel() ##falten chyya make it oned

array([0.41347616, 0.3939117 , 0.52663996, 0.31542709, 0.36748118,
       0.99429711, 0.46012885, 0.1928901 , 0.9712583 , 0.12581869,
       0.84606985, 0.54787334])

In [84]:
##manipulating rows and colums
m=np.arange(4).reshape(2,2)
m

array([[0, 1],
       [2, 3]])

In [45]:
b=np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [2]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [5]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [99]:
np.eye(4,4) ##identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
a.dtypearray([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
a.dtype
a.dtype

dtype('int32')

In [95]:
j=np.array(['apple','orange','grapes'],dtype='S')
j.dtype

dtype('S6')

In [96]:
j

array([b'apple', b'orange', b'grapes'], dtype='|S6')

In [97]:
k=np.array(['a','4','5'])
k

array(['a', '4', '5'], dtype='<U1')

In [98]:
k.dtype

dtype('<U1')

In [1]:
import numpy as np

In [4]:
new_data=np.random.randint(0,11,size=(3,4))
new_data

array([[ 0,  1, 10,  0],
       [10,  1,  4,  9],
       [ 3,  2,  5,  9]])

In [5]:
new_data.max()

10

In [6]:
new_data.min()

0

In [7]:
new_data.sum(axis=0)

array([13,  4, 19, 18])

In [9]:
new_data.sum(axis=1)

array([11, 24, 19])

In [3]:
arr=[1,2,3,4]
arr

[1, 2, 3, 4]

In [4]:
for x in arr:
    print(x)

1
2
3
4


In [5]:
for x in arr:
    if(x==3):
        print("3 is present in here")
    else:
        print("3 is not here")

3 is not here
3 is not here
3 is present in here
3 is not here


In [6]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
for x in a:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [23]:
b=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [24]:
for x in b:
    print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
for x in c:
    print(x)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [27]:
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8


In [28]:
for index,x in np.ndenumerate(arr):
    print(index,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [29]:
for index,x in np.ndenumerate(b):
    print(index,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 9
(0, 2, 1) 10
(0, 2, 2) 11
(0, 2, 3) 12


In [30]:
b.ndim

3

In [31]:
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [33]:
arr

[1, 2, 3, 4]

In [35]:
arr2=np.array_split(arr,2)
arr2

[array([1, 2]), array([3, 4])]

In [36]:
arr3=np.array_split(arr,3)
arr3

[array([1, 2]), array([3]), array([4])]

In [37]:
arr4=np.array_split(arr,4)
arr4

[array([1]), array([2]), array([3]), array([4])]

In [38]:
arr[0]

1

In [39]:
arr[3]

4

In [40]:
arr[2]

3

In [47]:
b=[1,2,3,4]
b

[1, 2, 3, 4]

In [62]:
a=np.where(arr == 4)
a

(array([3, 9], dtype=int64),)

In [56]:
arr = np.array([1,2,3,4,5,5,1,2,1,4,1,6,7])
arr

array([1, 2, 3, 4, 5, 5, 1, 2, 1, 4, 1, 6, 7])

In [57]:
np.where(arr==1)


(array([ 0,  6,  8, 10], dtype=int64),)

In [58]:
np.where(arr % 2==0)

(array([ 1,  3,  7,  9, 11], dtype=int64),)

In [59]:
np.sort(arr)

array([1, 1, 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 7])

In [64]:
j=np.array(['apple','orange','grapes'],dtype='S')
j

array([b'apple', b'orange', b'grapes'], dtype='|S6')

In [65]:
np.sort(j)

array([b'apple', b'grapes', b'orange'], dtype='|S6')

In [68]:
arr1=np.array([[1,2,3],[6,3,9]])
arr1

array([[1, 2, 3],
       [6, 3, 9]])

In [69]:
np.sort(arr1)

array([[1, 2, 3],
       [3, 6, 9]])

In [77]:
b=np.array([[[1,2,6,3],[5,4,7,8],[9,10,11,12]]])
b

array([[[ 1,  2,  6,  3],
        [ 5,  4,  7,  8],
        [ 9, 10, 11, 12]]])

In [78]:
np.sort(b)

array([[[ 1,  2,  3,  6],
        [ 4,  5,  7,  8],
        [ 9, 10, 11, 12]]])

In [79]:
arr1

array([[1, 2, 3],
       [6, 3, 9]])

In [80]:
x=[True,False]

In [1]:
import numpy as np

In [2]:
a=np.array([23,53,45,67])

In [3]:
x=[True,False,False,True]

In [5]:
new_a=a[x]

In [6]:
new_a

array([23, 67])

In [7]:
filter_array=[]

In [8]:
for i in a:
    if i > 46:
        filter_array.append(True)
    else:
        filter_array.append(False)    

In [9]:
filter_array

[False, True, False, True]

In [11]:
new_a=a[filter_array]
new_a

array([53, 67])

In [12]:
filter_array=a>46
filter_array

array([False,  True, False,  True])

In [13]:
filter2=a%2==0
filter2

array([False, False, False, False])

In [15]:
filter2=a%2!=0
filter2

array([ True,  True,  True,  True])

In [26]:
g=np.arange(12).reshape(2,6)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])